version: "3.4"

services:
  #frontend:
  #    container_name: frontend
  #    image: ${DOCKER_REGISTRY-}frontend:${PLATFORM:-linux}-${TAG:-latest}
  #    build:
  #        context: src/webapp/mover/
  #        dockerfile: Dockerfile
  #    depends_on:
  #        - envoy

  mover-api:
    container_name: mover-api
    image: ${DOCKER_REGISTRY-}moverapi:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/webapi/Mover/Dockerfile
    depends_on:
      - rabbitmq

  mover-api-dapr:
    container_name: mover-api-dapr
    image: "daprio/daprd:1.10.6"
    network_mode: "service:mover-api"
    depends_on:
      - mover-api
      - rabbitmq

  rabbitmq:
    container_name: rabbit
    image: rabbitmq:3-management-alpine
