version: "3.8"

services:
  frontend:
    ports:
      - "8081:80"

  mover-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PATH_BASE=/mover-api
      - PORT=80
    ports:
      - "5103:80"
    volumes:
      - "./src/webapi/Mover/temp/:/app/temp"

  mover-api-dapr:
    command:
      [
        "./daprd",
        "-app-id",
        "mover-api",
        "-app-port",
        "80",
        "-log-level",
        "debug",
        "-components-path",
        "/components",
        "-dapr-http-max-request-size",
        "8",
      ]
    volumes:
      - "./dapr/components/local/:/components"
      - "./src/webapi/Mover/temp/raw-files/:/app/temp/raw-files/"
      - "./src/webapi/Mover/temp/fit-files/:/app/temp/fit-files/"
      - "./src/webapi/Mover/temp/gpx-files/:/app/temp/gpx-files/"

  envoy:
    volumes:
      - ./src/apigateways/envoy:/etc/envoy
    ports:
      - "10000:10000"

  envoy-dapr:
    command:
      [
        "./daprd",
        "-app-id",
        "envoy",
        "-app-port",
        "10000",
        "-components-path",
        "/components",
      ]
    volumes:
      - "./dapr/components/:/components"

  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: "maia"
      RABBITMQ_DEFAULT_PASS: "beta80.1"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./storage/rabbitmqdata/lib/:/var/lib/rabbitmq/
      - ./storage/rabbitmqdata/log/:/var/log/rabbitmq/
