version: "3.4"

services:
    frontend:
        container_name: mover-fe
        image: ${DOCKER_REGISTRY-}mover-fe:${PLATFORM:-linux}-${TAG:-latest}
        build:
            context: frontend/mover/
            dockerfile: Dockerfile
            args:
                - VITE_APP_GATEWAY_URL=http://localhost:10000
        depends_on:
            - envoy

    mover-fitdecoder:
        container_name: mover-fitdecoder
        image: ${DOCKER_REGISTRY-}mover_fitdecoder:${PLATFORM:-linux}-${TAG:-latest}
        build:
            context: ./
            dockerfile: services/Mover.FitDecoder/Dockerfile
        depends_on:
            - rabbitmq

    mover-fitdecoder-dapr:
        container_name: mover-fitdecoder-dapr
        image: "daprio/daprd:1.10.6"
        network_mode: "service:mover-fitdecoder"
        depends_on:
            - mover-fitdecoder
            - rabbitmq

    mover-uploader:
        container_name: mover-uploader
        image: ${DOCKER_REGISTRY-}mover_uploader:${PLATFORM:-linux}-${TAG:-latest}
        build:
            context: ./
            dockerfile: services/Mover.Uploader/Dockerfile
        depends_on:
            - rabbitmq

    mover-uploader-dapr:
        container_name: mover-uploader-dapr
        image: "daprio/daprd:1.10.6"
        network_mode: "service:mover-uploader"
        depends_on:
            - mover-uploader
            - rabbitmq

    mover-stats:
        container_name: mover-stats
        image: ${DOCKER_REGISTRY-}mover_stats:${PLATFORM:-linux}-${TAG:-latest}
        build:
            context: ./
            dockerfile: services/Mover.Stats/Dockerfile
        depends_on:
            - rabbitmq

    mover-stats-dapr:
        container_name: mover-stats-dapr
        image: "daprio/daprd:1.10.6"
        network_mode: "service:mover-stats"
        depends_on:
            - mover-stats
            - rabbitmq

    mover-auth:
        container_name: mover-auth
        image: ${DOCKER_REGISTRY-}mover_auth:${PLATFORM:-linux}-${TAG:-latest}
        build:
            context: ./
            dockerfile: services/Mover.Auth/Dockerfile
        depends_on:
            - sqldata

    mover-auth-dapr:
        container_name: mover-auth-dapr
        image: "daprio/daprd:1.10.6"
        network_mode: "service:mover-auth"
        depends_on:
            - mover-auth
            - sqldata

    rabbitmq:
        container_name: rabbit
        image: rabbitmq:3-management-alpine

    envoy:
        container_name: envoy
        build:
            context: ./
            dockerfile: apigateways/envoy/Dockerfile

    envoy-dapr:
        container_name: envoy-dapr
        image: "daprio/daprd:1.10.6"
        network_mode: "service:envoy"
        depends_on:
            - envoy

    mongo:
        container_name: mongodb
        image: mongo:latest

    mongo-express:
        container_name: mongo-express
        image: mongo-express:latest

    sqldata:
        image: mcr.microsoft.com/azure-sql-edge