name: 2. Build and Publish FrontEnd to Registry
on:
  push:
    branches: ["main"]
    paths:
      - src/frontend/mover/**
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  ci-cd:
    uses: ./.github/workflows/build-publish.yml
    with:
      context: ./src/frontend/mover
      dockerfile: src/frontend/mover/Dockerfile
      image-name: mover-fe
    secrets: inherit
