name: 2. Build and Publish Auth to Registry
on:
  push:
    branches: ["main"]
    paths:
      - src/services/Mover.Auth/**
      - src/shared/**
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  ci-cd:
    uses: ./.github/workflows/build-publish.yml
    with:
      context: ./src
      dockerfile: src/services/Mover.Auth/Dockerfile
      image-name: mover-auth
    secrets: inherit
