name: 1. Setup Container registry
on:
  workflow_dispatch:
jobs:
  bicep-provision-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy bicep
        uses: azure/CLI@v1
        with:
          inlineScript: |
            if [ $(az group exists --name ${{ secrets.RESOURCE_GROUP }}) = false ]; then
              az group create -g ${{ secrets.RESOURCE_GROUP }} -l swedencentral
            fi
            az config set bicep.use_binary_from_path=false
            az bicep install
            az deployment group create -g ${{ secrets.RESOURCE_GROUP }} -f ./deploy/azure/setup-registry.bicep
